---
title: "Replication of Foundations of intuitive power analyses in children and adults by Pelz et al., 2022 (2022, Nature Human Behaviour)"
author: "Sophie Mazor (smazor@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

[No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense. 

My primary research interests revolve around children’s metacognition and belief revision. How do they recognize anomalies to their existing 
beliefs, and how do they acquire a sense of intellectual humility to recognize gaps in their own knowledge? Connected to this idea is knowing just 
how much information or certainty one may need in order to make a decision or revise an existing belief. This particular experiment provides evidence 
that both children and adults are able to do this-- they flexibly adjust their responses depending on the difficulty of a problem (i.e., predicting 
how much information is necessary to come to a decision). This result connects to some of the work I’m currently developing on children’s uncertainty 
tolerance. Instead of examining whether or not people are sensitive to the amount of information needed, I’m interested in how much uncertainty an 
individual is willing to have present when committing to a decision. Though this particular result shows a group level sensitivity to conducting an 
“intuitive power analysis,” it helps to inform my current work on behavior at the individual level. 
	This study broadly investigates whether children and adults can intuitively perform a power analysis (i.e., whether people are sensitive to the 
amount of evidence needed in order to make a particular inference or decision). In order to answer this question, participants are shown 10 pairs of 
boxes, each pair containing a different distribution of colored balls. There are 10 separate test trials, each displaying two boxes filled with 
colored balls with inverse proportions of one another (e.g., 95/5 vs. 5/95). The difficulty of the trials vary from 51/49 to 95/5, with the order 
randomized for each participant. On each trial, participants are shown two boxes, each belonging to a different character. They must enter a number for how many balls should be taken out of the boxes in order for them to determine which of the two boxes is being sampled. They measure whether participants adjust their sampling behavior as distributions get harder/easier to discriminate. 
	The primary challenge will be to redesign each of the stimuli, as there are 10 separate trials, with 200 visible balls across the two boxes per 
trial. Each trial has its own color scheme of balls inside, and it will be time consuming to replicate the boxes exactly as they appear in the 
original paper. The rest of the procedure should be fairly simple to recreate in terms of design.  

Repository: https://github.com/sophiemazor/pelz2022.git 


Original Paper: https://github.com/sophiemazor/pelz2022/tree/f8836bf68249a13be8bf75fb235c6bac3622d63d/original_paper



## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
